### #
_-$./"Skip to content"

meta:facebook

Pulls

Issues

Codespaces

Marketplace

Explore

 

"@lostleolotus#_-$./""

Your account is theeee shizzzzzi..

Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.

meta:facebook

Repositories309

Code0

Commits38K

Issues1

Discussions0

Packages0

Marketplace0

Topics0

Wikis0

Users0

Languages

53PHP

31JavaScript

23Python

15HTML

13Java

10Jupyter Notebook

10TypeScript

5Ruby

3CSS

2C++

Advanced search 

Search cheat sheet

GitHub’s search supports a variety of different operations. Here’s a quick cheat sheet for some of the common searches.

For more information, visit our search help section.

Basic search

This search	Finds repositories with…

cat stars:>100	Find cat repositories with greater than 100 stars.

user:defunkt	Get all repositories from the user defunkt.

tom location:"San Francisco, CA"	Find all tom users in "San Francisco, CA".

join extension:coffee	Find all instances of join in code with coffee extension.

NOT cat	Excludes all results containing cat.

Repository search 

Repository search looks through the projects you have access to on GitHub. You can also filter the results:

This search	Finds repositories with…

cat stars:>100	Find cat repositories with greater than 100 stars.

user:defunkt	Get all repositories from the user defunkt.

pugs pushed:>2013-01-28	Pugs repositories pushed to since Jan 28, 2013.

node.js forks:<200	Find all node.js repositories with less than 200 forks.

jquery size:1024..4089	Find jquery repositories between the sizes 1024 and 4089 kB.

gitx fork:true	Repository search includes forks of gitx.

gitx fork:only	Repository search returns only forks of gitx.

Code search 

Code search looks through the files hosted on GitHub. You can also filter the results:

This search	Finds repositories with…

install repo:charles/privaterepo	Find all instances of install in code from the repository charles/privaterepo.

shogun user:heroku	Find references to shogun from all public heroku repositories.

join extension:coffee	Find all instances of join in code with coffee extension.

system size:>1000	Find all instances of system in code of file size greater than 1000kbs.

examples path:/docs/	Find all examples in the path /docs/.

replace fork:true	Search replace in the source code of forks.

Issue search 

Issue search looks through issues and pull requests on GitHub. You can also filter the results:

This search	Finds issues…

encoding user:heroku	Encoding issues across the Heroku organization.

cat is:open	Find cat issues that are open.

strange comments:>42	Issues with more than 42 comments.

hard label:bug	Hard issues labeled as a bug.

author:mojombo	All issues authored by mojombo.

mentions:tpope	All issues mentioning tpope.

assignee:rtomayko	All issues assigned to rtomayko.

exception created:>2012-12-31	Created since the beginning of 2013.

exception updated:<2013-01-01	Last updated before 2013.

User search 

User search finds users with an account on GitHub. You can also filter the results:

This search	Finds repositories with…

fullname:"Linus Torvalds"	Find users with the full name "Linus Torvalds".

tom location:"San Francisco, CA"	Find all tom users in "San Francisco, CA".

chris followers:100..200	Find all chris users with followers between 100 and 200.

ryan repos:>10	Find all ryan users with more than 10 repositories.

309 repository results

HackerLoop/metatags-101

Meta tags templates. Optimize your website for sharing on Facebook, Twitter, Google+ and Pinterest.

 41

 HTML

Updated on Feb 21, 2018

acemtp/meteor-meta-extractor

Extract meta tags (opengraph / facebook, twitter, meta) from a html string or an url. Work on client and server.

 36

 JavaScript

MIT license

Updated on Sep 2, 2016

tucho235/grav-plugin-social-meta-tags

Facebook Open Graph and Twitter Cards Meta Tags

twitter-cards grav grav-plugin facebook-open-graph social-meta-tags

 8

 PHP

MIT license

Updated on Jul 19, 2017

lord-alfred/ipranges

hammer List all IP ranges from: Google (Cloud & GoogleBot), Bing (Bingbot), Amazon (AWS), Microsoft (Azure), Oracle (Cloud…

github microsoft digitalocean cloud facebook osint twitter bing azure oracle google-cloud cidr googlebot amazon-aws bingbot iplist ip-ranges github-actions cidr-ranges

 127

 Shell

CC0-1.0 license

Updated 15 hours ago

viswaah/vercel-redirect

It redirects the website request from facebook to any blog while keeping the meta data for the each link.

nextjs wordpress facebook redirect vercel

 8

 TypeScript

Updated on Oct 26

shipshapecode/ember-meta

Setup meta for your Prember/Ember blog to support opengraph, microdata, Facebook, Twitter, Slack etc.

ember blog meta twitter opengraph prember

 17

 JavaScript

MIT license

Updated 7 hours ago

chrisnharvey/CodeIgniter-Facebook-Spark

A Facebook library for CodeIgniter that allows you to make calls to the Facebook Graph API and easily integrate the meta

 14

 PHP

Updated on May 28, 2015

pabloroman/TNW-Social-Count

A WordPress plugin that saves the number of social shares of your articles (from Twitter, Facebook, LinkedIn & Google…

 15

 PHP

Updated on Jun 22, 2012

omegaes/Android-Link-Preview

An Android Library with demo application, to fetch meta-data from url, like Facebook and Whatsapp ....

android-library link-preview

 9

 Java

Updated on Aug 27, 2020

AlekseyPleshkov/nuxt-social-meta

Nuxt.js module generate meta-tags for social networks - Facebook, Twitter and LinkedIn (and the rest uses OG tags, su…

vuejs nuxtjs nuxt-module

 125

 JavaScript

Updated on Aug 23, 2021

         

Footer

© 2022 GitHub, Inc.

Footer navigation

Terms

Privacy

Security

Status

Docs

Contact GitHub

Pricing

API

Training

Blog

About

Search · meta:facebook"Place this data between the <head> tags of your website -->
<title>Page Title. Maximum length 60-70 characters</title>
<meta name="description" content="Page description. No longer than 155 characters." />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@publisher_handle">
<meta name="twitter:title" content="Page Title">
<meta name="twitter:description" content="Page description less than 200 characters">
<meta name="twitter:creator" content="@author_handle">
<!-- Twitter Summary card images must be at least 200x200px -->
<meta name="twitter:image" content="http://www.example.com/image.jpg">

<!-- Open Graph data -->
<meta property="og:title" content="Title Here" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://www.example.com/" />
<!-- Facebook image must be at least 600x315px -->
<meta property="og:image" content="http://example.com/image.jpg" />
<meta property="og:description" content="Description Here" />
<meta property="og:site_name" content="Site Name" />
<meta property="fb:admins" content="Facebook numeric ID" />
